<a href="https://colab.research.google.com/github/Risqi2112/Penelitian/blob/main/Preprocessing_Tanpa_Stopword(data_prediksi).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import nltk
!pip install unidecode textblob sastrawi
nltk.download('popular')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting unidecode
  Downloading Unidecode-1.3.6-py3-none-any.whl (235 kB)
     |████████████████████████████████| 235 kB 5.0 MB/s
Requirement already satisfied: textblob in /usr/local/lib/python3.8/dist-packages (0.15.3)
Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
     |████████████████████████████████| 209 kB 50.0 MB/s
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.8/dist-packages (from textblob) (3.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (1.2.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (4.64.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (2022.6.2)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (7.1.2)
Installing collected packages: unidecode, sastrawi
Successfully installed sastrawi-1.0.1 unidecode-1.3.6

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection popular

True

In [2]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
from html import unescape
from textblob import TextBlob

In [3]:
! mkdir -p /root/.ssh
with open("/root/.ssh/id_rsa", mode="w") as fp:
    fp.write("""
-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEA28vbY5SKh6JYjsRPhz0o8m1MeY8b/RdOekzRo6zwV64wCWnU
wGy4x5UaqdkPNz5YIoTE29FY2m9Yvo9iKsgy1tcPjDvat5z+sqGfySpZgLR9HIqH
Zebyma43IqNq/oscuSsiV2SJLYsLH+cTJQUvxxSK+V1Bj8dtWrenTNh4ASGzjLVF
lY8Az6K9PtCbp4uPAzVEkKhuG1axPjTVPVxnlanIpdhewkzL8oJnn8Oy+qRMmoFC
0WqedDPZ6bhnRit1n7xk6qzguIIxb5gBW4+fFOBskoZV5i3eHReM2XEjVr/gZXGk
uUuAZfxkhv00A2RTeJXzet2SfPCTmRYiV1BBovxXhj0GVC3vO4cOgMDAlWVmEyxW
3h1rf04y4O3vfai8FXXZXCdMWA1f1MhyydrPXOvIT3MZh/NwVZCnFG9sJojWtRSj
B/xgATP1hzmznqFNY6LGsJTqHtad/9FogLdy7t6WrpUzNsQhK/rwHOkqO7WGwRIC
rd+D7FozBmF443iCMEI37uGZpRdz12Jc6ocYQ28POwxeFFAO8Y+an5cyUCkuaWBD
20hotg6JchL/tFVSoNB2gmk/SPIJt7y01opuEDsdMtja6gdl6TF5+Ge/diQXyU5w
fo9r1pKGGRrG0ehcPrw/LRZcnbYOii+G5fnqDLgc7O3j7WtWtFDYXVHHlMECAwEA
AQKCAgB5fmvc1YTliGWvNPBI7xOtPaFiKCrucW2dyMywzq1jqhM/gNJrMy3IlLDS
Zfs1LC8HlaBDaarVw2qomxVGVLdVbjdX6tXxXMSk9RYf2lry+9GUbzZ8q3Y6YMR1
TyObZEYSTLeE2zvAgvU5Qz+f3QgV4VMYl+XflfrqhE3j+lwLNBfNlX3LN+rY2zoE
eMcxi8EXouAtngyO7BK5MfcVHfjcD6erlLh8anrpqA+jjkdmqF73oK/QlkDUNr0j
phzf+rHgBAE8fycQllbBOqK1e+QRZCRfsgXVYFFAf34Jy7IfB50ANhs5mXR161ee
DmQr488H/stBhSyuB0Vu/38oCGLesBK3OeseETeXOb1jWD+KJvKvSkGf04iIET4+
x91j3O5x1c1j/l3oC4b3FUH7iSvScpEM2znP7T+UWGxEUlKM2uEweSlksAnWowgl
qQIpqKW6iE6To7MHXl6d+nOmTezCIJ2yJvBnGQMIHUXU8zYAvfqtcO6GGxK1ByPV
NB14ezMrkkJWhlv87a/8rKhhNq8g2HvdryQ6XRwn8AmMpMSeOkPXL8X7/uaQEpzP
0KbpOqwSxhHTKpcqYHcwmrR16bq1cw7lndIkCqLCdhwOXhVG7YqniRAJUXxylUMm
S6onf7EjcyrtUU0+wzmw68tcqITSgwADhQQQ8NQuCEwIcSmbgQKCAQEA/VVoBbMd
UmC/pWUbP3eS+PdcfQgnYLzjf5OupZ8aH9La4hw17MGIwE4s7IjMJwr4im68TnrE
pnXRgzdFTUfEgjPr42gZadpptQN9aKLyKa0FaCmrmcKnv5zea7Y1VtyD7fMcKPxm
h4s2P7RgDeb520HSeZK/hKDC1mVP7mIdmSZOQeuQ//uWF2eFLOnMsN2ZS2lunK2W
7N6xZydx1ThvT0u5NcAn/dUaRmaZ3rTix+JZYPXtrGGNDpl2A5SOqfDN/UA82sS3
Cvmd7XdPzb6J100BpCJYjp5R6l0o3VqTQuK3tYbTYP15mGH/WXf0U2F8vMS0QK3L
ly3vmC066yjfmQKCAQEA3hwWEhvwM7IKaIwlihWIToUkTCsufwA/G2vK8AVXhOF+
DHVhgZssZwLMDagJ3O2twjXV0qtgPuQWvnf1eS8k8ep2IJT2nkqUZP2mtFU+pPFY
PHFgJ4AWu2CHcppccH6PXc6sd1yMsmM2ck4Nm6CCp6IPzDya4q0dboprsqgafCiL
ZSfTezA31YrQN+4CGXIV2nWaKATiZ3s8TFanDJPwxfiOeXvxVMNNXGBHovPQSI6O
kYRx4bIY1TkoJGuJii+PAJeL6mLnEc0kofdZMtiCG/a9283Fbq2h7ey7nXwqOX2E
53Cl1HJ9R+M1q94uIOtHEYCRoCQR4T0rzsXXago3aQKCAQEA9nzhB5qtTvffwHfN
uUUI9cEIdoc2eUOQPxNcfL1/V7N7UUGNnlz4R9RIlaTMrrhX96mjAuEk8an1PqzK
e1T2+JC4Vb117K6c54kLvoG9CZvVhPH2i1cAjMl/CGJzJ57LpvxCTAa5Y+ypzfYc
96njNdinh66nNc6NhLlyukkw71B8GFux67/I2+DXjUm25efXPa7J9xxXmwVaqzmP
4pxUgVz2Sjw7LRjpxdISqMRrW3z65gKjTHRmIOxkDTvAS82HP3//NgTs7HrPlLvg
JBneWGQO0rqwW6PjpBscpbN5UTzy7mbOyLIYW5ION+klCvPxwGHL2JrBWslRNEnd
5+0PEQKCAQB7OgnksitqAvVTW63YFmoxZhzlRW/edjyM8hj9YXlU9+X+84DNb1IL
NLoROZF/ST6F6WhgIUScn98efV9rhIRy0yoGmZ7Z43bBMRk0I7dFu8DAiAZY4++4
ta1wH8P5hb30xZ1Z+7bzoaerczKJjVvvtTIeleE4seMKWTG3RRyslbIAxT/HsNDJ
YOJ0pU/03h7RvT1xxoP19aFWmRzFFa8Xpvck32bdKB3bim80MSD1oGHoyhqEpVKx
uaxTyHXefNRR98Jgn86jSbVxRtHuK8DD0vky4c8PwLV+U0Ej9qdWjhUWcqEOZRas
s5oraHEfQmmDhFlHB7wDwvRzG8CPzGtBAoIBAQDFtk7V82kV8UfH3S6uT59dhEqm
SD3tyMxvphtix+s4FFBJMzRSVaHZ6zGYoaDQZ2tpFz1VTlFn7tXH0kaHLjhqtbWA
0gJ6PHRbN54L0UO1Y1i0UPKCpNyaaG8dwoyP+2fKhLmrpdwIXXKBIwV4qzOT+nyI
xNsauYFduDHq3jmr3Pq3NF/xk6JFtxutk9vPB6a7sBrEFsm/Zhbuw/s2VV4R2R9o
LiK/e3Tlgk53XK4d16jlsNhvPqv8HbwTkTTg1sjYtzSBnuLQOZCTy7JPy2zr60+i
ZPFl/76wVF9oVruNH6m8y5mFNMDCKsf7Q+SQmb+QdlHGSt5M+KJam4jS2QZL
-----END RSA PRIVATE KEY-----
""")
! ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
! chmod go-rwx /root/.ssh/id_rsa
! git clone git@github.com:Risqi2112/Penelitian.git
%cd /content/Penelitian

# github.com:22 SSH-2.0-babeld-408889af
Cloning into 'Penelitian'...
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
remote: Enumerating objects: 448, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 448 (delta 49), reused 0 (delta 0), pack-reused 331
Receiving objects: 100% (448/448), 2.45 MiB | 8.94 MiB/s, done.
Resolving deltas: 100% (166/166), done.
/content/Penelitian

In [4]:
Data_predict = pd.read_csv('/content/Penelitian/Analisis_Sentimen_PPDB_2018_2022/Data/Unlabeled_data.csv',sep=';')
Data_predict.head()

   tahun                                               text
0   2018  Cara Pendaftaran dan Pengumuman Hasil Seleksi ...
1   2018  Come and join us... \n\nPPDB SMK Telkom Jakart...
2   2018  Info pendaftaran PPDB SMK Telkom Jakarta TA 20...
3   2018  'Radar Bogor : Catat, Ini Rekomendasi Ombudsma...
4   2018  Hii, doain aku supaya aku keterima ppdb di SMA...

In [5]:
#sns.countplot(x="sentimen", data=Data_predict,)

In [6]:
Data_predict.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8181 entries, 0 to 8180
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tahun   8181 non-null   int64
 1   text    8181 non-null   object
dtypes: int64(1), object(1)
memory usage: 128.0+ KB

Clean text

In [7]:
def filtering(text):
    text = re.sub(r'http\S+', '', text)   # Remove link web
    text = re.sub('@[^\s]+', '', text)    # Remove @username
    text = re.sub(r'#([^\s]+)', '', text) # Remove #tagger
    text = text.replace('\\t', " ").replace('\\n', " ").replace('\\u', " ").replace('\\', " ") # Remove tab, new line \n, ans back slice
    text = re.sub(r'[^\x00-\x7f]', r'', text) # Remove angka termasuk angka yang berada dalam string & Remove non ASCII chars
    text = re.sub(r'(\\u[0-9A-Fa-f]+)', r'', text)
    text = re.sub(r"[^A-Za-z0-9^,!.\/'+-=]", " ", text)
    text = re.sub(r'\\u\w\w\w\w', '', text)
    text = re.sub(r"[.,:;+!\-_<^/=?\"'\(\)\d\*]", " ", text) # Remove simbol, angka dan karakter aneh
    text = str(text).lower() # mengubah ke huruf non kapital
    text = (re.compile(r"(.)\1{1,}", re.DOTALL).sub(r"\1\1", text)) # Pola untuk mencari tiga atau lebih pengulangan karakter apapun, termasuk baris baru (contoh goooool -> gool)
    text = re.sub(r"\b[a-zA-Z]\b", "", text) # Remove karakter tunggal, contoh : r

    return text

Data_predict['Filtering'] = Data_predict.text.apply(lambda x:filtering(x))
Data_predict.head()

,tahun,text,Filtering
0,2018,Cara Pendaftaran dan Pengumuman Hasil Seleksi ...,cara pendaftaran dan pengumuman hasil seleksi ...
1,2018,Come and join us... \n\nPPDB SMK Telkom Jakart...,come and join us ppdb smk telkom jakarta smk...
2,2018,Info pendaftaran PPDB SMK Telkom Jakarta TA 20...,info pendaftaran ppdb smk telkom jakarta ta u...
3,2018,"'Radar Bogor : Catat, Ini Rekomendasi Ombudsma...",radar bogor catat ini rekomendasi ombudsman...
4,2018,"Hii, doain aku supaya aku keterima ppdb di SMA...",hii doain aku supaya aku keterima ppdb di sma...

Mengubah kata-kata slang/singkatan menjadi kata baku & Tokenisasi

In [8]:
df = open('/content/Penelitian/Analisis_Sentimen_PPDB_2018_2022/data_slang.txt')
slangs = df.readlines(); df.close()
slangs = [t.strip('\n').strip() for t in slangs]
slangs = [t.split(":") for t in slangs]
slangs = [[k.strip(), v.strip()] for k,v in slangs]
slangs = {k:v for k,v in slangs}

def singkatan(text):
    text = TextBlob(text).words
    for i,t in enumerate(text):
      if t in slangs.keys():
          text[i] = slangs[t]
    return text

Data_predict['Non_Singkatan'] = Data_predict['Filtering'].apply(lambda x:singkatan(x))
Data_predict.head()

,tahun,text,Filtering,Non_Singkatan
0,2018,Cara Pendaftaran dan Pengumuman Hasil Seleksi ...,cara pendaftaran dan pengumuman hasil seleksi ...,"[cara, pendaftaran, dan, pengumuman, hasil, se..."
1,2018,Come and join us... \n\nPPDB SMK Telkom Jakart...,come and join us ppdb smk telkom jakarta smk...,"[come, and, join, us, ppdb, smk, telekomunikas..."
2,2018,Info pendaftaran PPDB SMK Telkom Jakarta TA 20...,info pendaftaran ppdb smk telkom jakarta ta u...,"[informasi, pendaftaran, ppdb, smk, telekomuni..."
3,2018,"'Radar Bogor : Catat, Ini Rekomendasi Ombudsma...",radar bogor catat ini rekomendasi ombudsman...,"[radar, bogor, catat, ini, rekomendasi, ombuds..."
4,2018,"Hii, doain aku supaya aku keterima ppdb di SMA...",hii doain aku supaya aku keterima ppdb di sma...,"[hii, doain, aku, supaya, aku, keterima, ppdb,..."

Stop Removal

In [9]:
stopword = nltk.corpus.stopwords.words('indonesian')


def remove_stopwords(text):
    text = [word for word in text if word not in stopword]
    return text

Data_predict['Stop_Removal'] = Data_predict['Non_Singkatan'].apply(lambda x: remove_stopwords(x))
Data_predict.head()

,tahun,text,Filtering,Non_Singkatan,Stop_Removal
0,2018,Cara Pendaftaran dan Pengumuman Hasil Seleksi ...,cara pendaftaran dan pengumuman hasil seleksi ...,"[cara, pendaftaran, dan, pengumuman, hasil, se...","[pendaftaran, pengumuman, hasil, seleksi, ppdb..."
1,2018,Come and join us... \n\nPPDB SMK Telkom Jakart...,come and join us ppdb smk telkom jakarta smk...,"[come, and, join, us, ppdb, smk, telekomunikas...","[come, and, join, us, ppdb, smk, telekomunikas..."
2,2018,Info pendaftaran PPDB SMK Telkom Jakarta TA 20...,info pendaftaran ppdb smk telkom jakarta ta u...,"[informasi, pendaftaran, ppdb, smk, telekomuni...","[informasi, pendaftaran, ppdb, smk, telekomuni..."
3,2018,"'Radar Bogor : Catat, Ini Rekomendasi Ombudsma...",radar bogor catat ini rekomendasi ombudsman...,"[radar, bogor, catat, ini, rekomendasi, ombuds...","[radar, bogor, catat, rekomendasi, ombudsman, ..."
4,2018,"Hii, doain aku supaya aku keterima ppdb di SMA...",hii doain aku supaya aku keterima ppdb di sma...,"[hii, doain, aku, supaya, aku, keterima, ppdb,...","[hii, doain, keterima, ppdb, sman, jakarta, am..."

Mengubah ke bentuk text

In [10]:
def fit_stopwords(text):
    text = np.array(text)
    text = ' '.join(text)
    return text

Data_predict['Stop_Removal'] = Data_predict['Stop_Removal'].apply(lambda x:fit_stopwords(x))
Data_predict.head()

,tahun,text,Filtering,Non_Singkatan,Stop_Removal
0,2018,Cara Pendaftaran dan Pengumuman Hasil Seleksi ...,cara pendaftaran dan pengumuman hasil seleksi ...,"[cara, pendaftaran, dan, pengumuman, hasil, se...",pendaftaran pengumuman hasil seleksi ppdb onli...
1,2018,Come and join us... \n\nPPDB SMK Telkom Jakart...,come and join us ppdb smk telkom jakarta smk...,"[come, and, join, us, ppdb, smk, telekomunikas...",come and join us ppdb smk telekomunikasi jakar...
2,2018,Info pendaftaran PPDB SMK Telkom Jakarta TA 20...,info pendaftaran ppdb smk telkom jakarta ta u...,"[informasi, pendaftaran, ppdb, smk, telekomuni...",informasi pendaftaran ppdb smk telekomunikasi ...
3,2018,"'Radar Bogor : Catat, Ini Rekomendasi Ombudsma...",radar bogor catat ini rekomendasi ombudsman...,"[radar, bogor, catat, ini, rekomendasi, ombuds...",radar bogor catat rekomendasi ombudsman pelaks...
4,2018,"Hii, doain aku supaya aku keterima ppdb di SMA...",hii doain aku supaya aku keterima ppdb di sma...,"[hii, doain, aku, supaya, aku, keterima, ppdb,...",hii doain keterima ppdb sman jakarta amin semoga

Stemming

In [11]:
#from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
#factory = StemmerFactory()
#stemmer = factory.create_stemmer()

#def stemming(text):
#    return stemmer.stem(text)

#Data_predict['Stemming'] = Data_predict['Stop_Removal'].apply(lambda x:stemming(x))
#Data_predict.head(150)

In [12]:
#Data_predict.drop(['text'],inplace=True,axis=1)
#Data_predict.drop(['Filtering'],inplace=True,axis=1)
#Data_predict.drop(['Non_Singkatan'],inplace=True,axis=1)
#Data_predict.drop(['Stop_Removal'],inplace=True,axis=1)
#Data_predict['teksbersih'] = Data_predict['Stemming']
#Data_predict.drop(['Stemming'],inplace=True,axis=1)
#Data_predict.head()

In [13]:
Data_predict.drop(['text'],inplace=True,axis=1)
Data_predict.drop(['Filtering'],inplace=True,axis=1)
Data_predict.drop(['Non_Singkatan'],inplace=True,axis=1)
Data_predict['tweet_bersih'] = Data_predict['Stop_Removal']
Data_predict.drop(['Stop_Removal'],inplace=True,axis=1)
#Data_predict.drop(['Stemming'],inplace=True,axis=1)
Data_predict.head()

   tahun                                       tweet_bersih
0   2018  pendaftaran pengumuman hasil seleksi ppdb onli...
1   2018  come and join us ppdb smk telekomunikasi jakar...
2   2018  informasi pendaftaran ppdb smk telekomunikasi ...
3   2018  radar bogor catat rekomendasi ombudsman pelaks...
4   2018   hii doain keterima ppdb sman jakarta amin semoga

In [14]:
Data_predict.to_csv('Data_prediksi.csv', index = False)